const ERROR_CODES = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INVALID_URL: "INVALID_URL",
  INVALID_PATH: "INVALID_PATH",
  UNSUPPORTED_URL: "UNSUPPORTED_URL",
  VIDEO_UNAVAILABLE: "VIDEO_UNAVAILABLE",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  HTTP_403: "HTTP_403",
  HTTP_412: "HTTP_412",
  NETWORK_CONNECTION_REFUSED: "NETWORK_CONNECTION_REFUSED",
  FFMPEG_NOT_FOUND: "FFMPEG_NOT_FOUND",
  FORMAT_NOT_AVAILABLE: "FORMAT_NOT_AVAILABLE",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  PROCESS_FAILED: "PROCESS_FAILED"
};

module.exports = ERROR_CODES;
